k8s_packages:
  - docker
  - kubelet
  - kubeadm
  - kubectl
  - helm

kube_version: v1.29.3

nginx_release_name: nginx
prometheus_release_name: prometheus
grafana_release_name: grafana
node_exporter_release_name: node-exporter


prometheus_values:
  scrape_interval: 15s
  node_exporter_target: localhost:9100

grafana_values:
  admin_user: admin
  admin_password: admin
  service_type: NodePort
  service_port: 3000

node_exporter_values:
  service_port: 9100


kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config') }}"
kube_context: "kubernetes-admin@kubernetes" # Replaced with your Kubernetes context
namespace: "sdv" # Replace with the namespace where your MySQL pod is running
mysql_app_label: "app=mysql" # Label to identify your MySQL pod (e.g., from your deployment)

    # --- MySQL Database Details ---
mysql_root_password: "Pa$$W0Rd654#" # IMPORTANT: Replace with your actual MySQL root password
new_database_name: "data_vault"
new_user_name: "dvuser"
new_user_password: "nsdl1234"
grant_user_name: "dvuser" # User for the grant command, adjust if different from new_user_name