- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
  become: yes

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Recreate kube-apiserver manifest if missing
  ansible.builtin.template:
    src: kube-apiserver.yaml.j2
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    mode: '0644'
  when: private_ip is defined
  become: yes

- name: Pause after recreating kube-apiserver manifest
  ansible.builtin.pause:
    seconds: 5
  when: private_ip is defined
  become: yes
