- name: Create sdv namespace
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: midware
    validate_certs: no
    kubeconfig: /etc/kubernetes/admin.conf
  become: true
  become_user: root

- name: Deploy Frontend
  kubernetes.core.k8s:
    src: "{{ playbook_dir }}/../roles/frontend/templates/frontend.yml"
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    validate_certs: no
  become: true
  become_user: root

- name: Deploy Middleware
  kubernetes.core.k8s:
    src: "{{ playbook_dir }}/../roles/frontend/templates/middleware.yml"
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    validate_certs: no
  become: true
  become_user: root