- name: Ensure python3 is installed using raw (no Python required)
  raw: |
    if ! command -v python3 &> /dev/null; then
      yum install -y python3
    fi

- name: Ensure /usr/bin/python exists (symlink to python3)
  raw: |
    if [ ! -f /usr/bin/python ] && [ -f /usr/bin/python3 ]; then
      ln -s /usr/bin/python3 /usr/bissn/python
    fi
