apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  # namespace: sdv
  labels:
    type: local
spec:
  storageClassName: sdv-local-storage
  capacity:
    storage: 4Gi ###Change as per requirement
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/data" ###Change location as per requirement
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ k8s_node_name }}"   # This must resolve to the node name where volume exists
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - vunetpock8sworker2
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: sdv
spec:
  storageClassName: sdv-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi ###Change as per requirement and according to above PV storage size 