---
- name: Include prerequisites tasks
  include_tasks: prerequisites.yml

- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

- name: Deploy Prometheus ConfigMap and Deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/prometheus-deployment.yml.j2') | from_yaml_all | select('defined') | list }}"
  register: prometheus_deploy

- name: Wait for Prometheus deployment to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: prometheus
    namespace: monitoring
  register: prometheus_status
  until: 
    - prometheus_status.resources is defined
    - prometheus_status.resources | length > 0
    - prometheus_status.resources[0].status.availableReplicas is defined
    - prometheus_status.resources[0].status.availableReplicas > 0
  retries: 30
  delay: 10

- name: Deploy Node Exporter DaemonSet
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/node-exporter-daemonset.yml.j2') | from_yaml_all | select('defined') | list }}"
  register: node_exporter_deploy

- name: Wait for Node Exporter DaemonSet to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: DaemonSet
    name: node-exporter
    namespace: monitoring
  register: node_exporter_status
  until: 
    - node_exporter_status.resources is defined
    - node_exporter_status.resources | length > 0
    - node_exporter_status.resources[0].status.numberReady is defined
    - node_exporter_status.resources[0].status.numberReady > 0
  retries: 30
  delay: 10

- name: Deploy Node Exporter Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/node-exporter-service.yml.j2') | from_yaml_all | select('defined') | list }}"
