# -- Image name and version
image:
  pullPolicy: IfNotPresent
  repository: elasticsearch
  tag: 7.17.8

# -- Count of replicas
replicas: 1

# -- Cluster name
clusterName: logs

#-- Storage Class Name
storageClassName: sdv-local-storage

security:
  # -- Enable security
  enabled: true
  # -- Default username
  name: logging
  # -- Default password
  password: qwerty

ports:
  # -- ElasticSearch REST port
  http: 9200
  # -- ElasticSearch internal node communication port
  communication: 9300
  # -- If define, create NodePort for external usage
  external: 32200

resources:
  # # -- Requested resources
  # requests:
  #   cpu: 200m
  #   memory: 1024Mi
  # # -- Limited resources
  # limits:
  #   cpu: 200m
  #   memory: 1024Mi

  # -- Requested resources
  requests:
    cpu: 100m
    memory: 2Gi
  # -- Limited resources
  limits:
    cpu: 100m
    memory: 2Gi