---
- name: MySQL Setup Playbook
  hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml



  tasks:
    - name: Create sdv namespace
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: "{{ namespace }}"
        validate_certs: no
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Deploy storage class
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../roles/mysql/templates/storageclass.yml"
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        validate_certs: no

    - name: Deploy PV & PVC
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../roles/mysql/templates/mysql-pv-pvc.yml"
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        validate_certs: no

    - name: Deploy MySQL Deployment and Service
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../roles/mysql/templates/mysql-deploy-and-svc.yml"
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        validate_certs: no

    - name: Deploy MySQL DB credentials secret
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../roles/mysql/templates/mysql-db-secret.yml"
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        validate_certs: no

    - name: Run MySQL Configuration Logic
      include_tasks: "{{ playbook_dir }}/../roles/mysql/tasks/configure-mysql.yml"
