apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    type: local
spec:
  storageClassName: sdv-local-storage # Must match your StorageClass name
  capacity:
    storage: 4Gi # Must be equal to or greater than the PVC request
  accessModes:
   - ReadWriteOnce # Must match the PVC request
  hostPath:
    path: "/mnt/data/grafana" # This path must exist on your VM
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ k8s_node_name.stdout }}"   # This must resolve to the node name where volume exists
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: sdv-local-storage