- name: Install Grafana
  kubernetes.core.helm:
    name: "{{ pro_graf_grafana_chart_name }}"
    chart_ref: "{{ pro_graf_grafana_chart_ref }}"
    release_namespace: "{{ pro_graf_release_namespace }}"
    kubeconfig: /etc/kubernetes/admin.conf
    values:
      service:
        type: "{{ pro_graf_grafana_server_service_type }}"
      persistence:
        enabled: true
        storageClassName: sdv-local-storage
        accessModes:
          - ReadWriteOnce
        size: "8Gi"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
  become: true
  become_user: root