  # Step: Install Kubernetes pre-requisite packages with OS-aware logic

- name: Install Kubernetes pre-requisite packages on Debian/Ubuntu
  apt:
    name:
      - conntrack
      - socat
      - iproute2
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
  become: true

- name: Install Kubernetes pre-requisite packages on CentOS/RHEL
  yum:
    name:
      - conntrack
      - socat
      - iproute
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == "yum"
  become: true

- name: Install Kubernetes pre-requisite packages on Fedora
  dnf:
    name:
      - conntrack
      - socat
      - iproute-tc
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == "dnf"
  become: true

- name: Install Kubernetes pre-requisite packages on Alpine Linux
  apk:
    name:
      - conntrack-tools
      - socat
      - iproute2
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == "apk"
  become: true

- name: Fail if unsupported OS
  fail:
    msg: "Unsupported OS or package manager: {{ ansible_pkg_mgr }}. Please update the playbook."
  when: ansible_pkg_mgr not in ["apt", "yum", "dnf", "apk"]
