- name: Deploy SDV stack on Kubernetes
  hosts: local
  become: true
  become_user: root
  gather_facts: true
  roles:
    - OSdetection
    - python
    - k8s_setup
    - monitoring
    - mysql
    - frontend
