- name: Deploy SDV stack on Kubernetes
  hosts: local
  become: true
  become_user: root
  gather_facts: true

  pre_tasks:
    - name: Create logs directory
      ansible.builtin.file:
        path: "{{ playbook_dir }}/../logs"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

  roles:
    - OSdetection
    - python
    - k8s_setup
    - monitoring
    - mysql
    # - frontend
    # - pro-graf
